topics:
  - "Eurozone-USA relations"
  - "Global News"
  - "USA"
  - "Global markets"
  - "China"
  - "Europe"
  - "South Africa"
  - "Global News"
  - "Tech"
  - "AI"
  - "US, EU & SA Markets"
  - "US, UK, Eurozon & SA Politics"

model: "gpt-4.1-mini"

output:
  # lambda
  # root: "/tmp/reports"
  # local
  root: "reports"

img:
  generate_image: true
  resolution: "news_article - medium resolution" #  "instagram_feed"

audio:
  generate_audio: true
  voice: "onyx"
  model: "gpt-4o-mini-tts"
  script_model: "gpt-4.1-nano"

s3:
  bucket_name: "younews-reports"